In [1]:
# Dependencies
import torch

import numpy as np

%matplotlib inline

In [2]:
# Create an uninitialized tensor, which has garbage and datatype float32.
x = torch.empty(size=(3, 4, 2))  # torch.empty(3, 4, 2). Also, torch.Tensor(3, 4, 2) works!
print('empty tensor: {}'.format(x))
print('empty tensor type: {}'.format(x.dtype))
print('empty tensor shape: {}'.format(x.shape))

empty tensor: tensor([[[ 1.2416e-29,  1.4013e-45],
         [ 4.9045e-44,  1.4013e-45],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  1.1704e-41]],

        [[ 0.0000e+00,  2.2369e+08],
         [ 0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00],
         [        nan,         nan]],

        [[ 1.9933e-32,         nan],
         [ 2.2369e+08,  2.2369e+08],
         [-2.2439e+32,  4.5782e-41],
         [ 0.0000e+00,  0.0000e+00]]])
empty tensor type: torch.float32
empty tensor shape: torch.Size([3, 4, 2])


In [3]:
# Create a tensor of all ones. Analogously, torch.zeros works too.
ones = torch.ones(size=(3, 4, 2))
print('all ones tensor: {}'.format(ones))
print('all ones tensor type: {}'.format(ones.dtype))
print('all ones tensor shape: {}'.format(ones.shape))
zeros = torch.zeros(4, 2, 3)
print('all zeros tensor: {}'.format(zeros))
print('all zeros tensor type: {}'.format(zeros.dtype))
print('all zeros tensor shape: {}'.format(zeros.shape))

all ones tensor: tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])
all ones tensor type: torch.float32
all ones tensor shape: torch.Size([3, 4, 2])
all zeros tensor: tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
all zeros tensor type: torch.float32
all zeros tensor shape: torch.Size([4, 2, 3])


In [4]:
# Random floats from [0.0, 1.0) range.
torch.manual_seed(seed=7)
x = torch.rand(size=(3, 4, 2))
print('random tensor: {}'.format(x))
print('random tensor type: {}'.format(x.dtype))
print('random tensor shape: {}'.format(x.shape))
torch.manual_seed(seed=7)
x_again = torch.rand(size=(3, 4, 2))
print('random tensor: {}'.format(x))
print('random tensor type: {}'.format(x.dtype))
print('random tensor shape: {}'.format(x.shape))  # Identical results with manual seed.
# noinspection PyTypeChecker
print('both tensor values are the same: {}'.format(torch.all(x==x_again)))

random tensor: tensor([[[0.5349, 0.1988],
         [0.6592, 0.6569],
         [0.2328, 0.4251],
         [0.2071, 0.6297]],

        [[0.3653, 0.8513],
         [0.8549, 0.5509],
         [0.2868, 0.2063],
         [0.4451, 0.3593]],

        [[0.7204, 0.0731],
         [0.9699, 0.1078],
         [0.8829, 0.4132],
         [0.7572, 0.6948]]])
random tensor type: torch.float32
random tensor shape: torch.Size([3, 4, 2])
random tensor: tensor([[[0.5349, 0.1988],
         [0.6592, 0.6569],
         [0.2328, 0.4251],
         [0.2071, 0.6297]],

        [[0.3653, 0.8513],
         [0.8549, 0.5509],
         [0.2868, 0.2063],
         [0.4451, 0.3593]],

        [[0.7204, 0.0731],
         [0.9699, 0.1078],
         [0.8829, 0.4132],
         [0.7572, 0.6948]]])
random tensor type: torch.float32
random tensor shape: torch.Size([3, 4, 2])
both tensor values are the same: True


In [5]:
# Random ranged integers.
torch.manual_seed(seed=7)
x = torch.randint(low=0, high=10, size=(3, 4))
print('random integer tensor: {}'.format(x))
print('random integer tensor type: {}'.format(x.dtype))
print('random integer tensor shape: {}'.format(x.shape))

random integer tensor: tensor([[5, 2, 1, 6],
        [3, 7, 7, 9],
        [8, 1, 8, 1]])
random integer tensor type: torch.int64
random integer tensor shape: torch.Size([3, 4])


In [6]:
# Create tensors of the same shape.
torch.manual_seed(seed=7)
x = torch.rand(size=(3, 2, 4))
print('*'*79)
print('x: {}'.format(x))
x_empty = torch.empty_like(x)
print('*'*79)
print('empty tensor like x: {}'.format(x_empty))
print('empty tensor type like x: {}'.format(x_empty.dtype))
print('empty tensor shape like x: {}'.format(x_empty.shape))
x_ones = torch.ones_like(x)
print('*'*79)
print('all ones tensor like x: {}'.format(x_ones))
print('all ones tensor type like x: {}'.format(x_ones.dtype))
print('all ones tensor shape like x: {}'.format(x_ones.shape))
x_zeros = torch.zeros_like(x)
print('*'*79)
print('all zeros tensor like x: {}'.format(x_zeros))
print('all zeros tensor type like x: {}'.format(x_zeros.dtype))
print('all zeros tensor shape like x: {}'.format(x_zeros.shape))
x_rand = torch.rand_like(x)
print('*'*79)
print('random tensor like x: {}'.format(x_rand))
print('random tensor type like x: {}'.format(x_rand.dtype))
print('random tensor shape like x: {}'.format(x_rand.shape))
x_randint = torch.randint_like(input=x, low=0, high=10)  # The data type is cast to that of x, which is float32!
print('*'*79)
print('random integer tensor like x: {}'.format(x_randint))
print('random integer tensor like x type: {}'.format(x_randint.dtype))
print('random integer tensor like x shape: {}'.format(x_randint.shape))
x_randint = torch.randint_like(input=x, low=0, high=10, dtype=torch.int32)
print('*'*79)
print('random integer tensor like x: {}'.format(x_randint))
print('random integer tensor like x type : {}'.format(x_randint.dtype))
print('random integer tensor like x shape: {}'.format(x_randint.shape))

*******************************************************************************
x: tensor([[[0.5349, 0.1988, 0.6592, 0.6569],
         [0.2328, 0.4251, 0.2071, 0.6297]],

        [[0.3653, 0.8513, 0.8549, 0.5509],
         [0.2868, 0.2063, 0.4451, 0.3593]],

        [[0.7204, 0.0731, 0.9699, 0.1078],
         [0.8829, 0.4132, 0.7572, 0.6948]]])
*******************************************************************************
empty tensor like x: tensor([[[0.5349, 0.1988, 0.6592, 0.6569],
         [0.2328, 0.4251, 0.2071, 0.6297]],

        [[0.3653, 0.8513, 0.8549, 0.5509],
         [0.2868, 0.2063, 0.4451, 0.3593]],

        [[0.7204, 0.0731, 0.9699, 0.1078],
         [0.8829, 0.4132, 0.7572, 0.6948]]])
empty tensor type like x: torch.float32
empty tensor shape like x: torch.Size([3, 2, 4])
*******************************************************************************
all ones tensor like x: tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1.

In [7]:
# Creating a tensor from the data given.
# The tensor stores its own copy of the data.
# Note different containers used (lists and tuples).
x = torch.tensor(
    data=(
        ([1, 2, 3], (3, 4, 5)),
        ([5, 6, 7], (7, 8, 9)),
        [[10, 11, 12], [13, 14, 15]],
        ((16, 17, 18), (19, 20, 21))
    ), dtype=torch.float32
)
print('x from data: {}'.format(x))
print('x from data type: {}'.format(x.dtype))
print('x from data shape: {}'.format(x.shape))

x from data: tensor([[[ 1.,  2.,  3.],
         [ 3.,  4.,  5.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.]],

        [[16., 17., 18.],
         [19., 20., 21.]]])
x from data type: torch.float32
x from data shape: torch.Size([4, 2, 3])


In [8]:
# Data types by specifying the `dtype` parameter.
x = torch.rand(size=(3, 4), dtype=torch.float)  # floatX works, intX doesn't!
print('x: {}, type: {}'.format(x, x.dtype))
x = torch.randint(low=0, high=10, size=(3, 4), dtype=torch.float32)  # intX and floatX work!
print('x: {}, type: {}'.format(x, x.dtype))
x = torch.randint(low=0, high=10, size=(3, 4), dtype=torch.int)  # intX and floatX work!
print('x: {}, type: {}'.format(x, x.dtype))
# Data type by casting via attributes float(), int(), bool().
x = torch.rand(size=(3, 4)).float()  # Casts to float32.
print('x: {}, type: {}'.format(x, x.dtype))
x = torch.rand(size=(3, 4)).int()  # Casts to int32. So, it will all be zero! (why?)
print('x: {}, type: {}'.format(x, x.dtype))
x = torch.rand(size=(3, 4)).bool()  # Casts to bool. So, it will all be True! (why?)
print('x: {}, type: {}'.format(x, x.dtype))
x = torch.rand(size=(3, 4)).int().bool()  # Casts to int32 and then to bool. So, it will all be False! (why?)
print('x: {}, type: {}'.format(x, x.dtype))
# Creating a random bool tensor of `True` and `False` values.
x = torch.randint(low=0, high=2, size=(3, 4, 2), dtype=torch.bool)
print('x: {}, type: {}'.format(x, x.dtype))
# Casting with the `.to(<...>)` attribute.
x = torch.randint(low=0, high=10, size=(3, 4))
print('*'*79)
print('x: {}, type: {}'.format(x, x.dtype))
print('*'*79)
x_int = x.to(torch.int)
print('x_int: {}, type: {}'.format(x_int, x_int.dtype))
x_int8 = x.to(torch.int8)
print('x_int8: {}, type: {}'.format(x_int8, x_int8.dtype))
x_int16 = x.to(torch.int16)
print('x_int16: {}, type: {}'.format(x_int16, x_int16.dtype))
x_int32 = x.to(torch.int32)
print('x_int32: {}, type: {}'.format(x_int32, x_int32.dtype))
x_int64 = x.to(torch.int64)
print('x_int64: {}, type: {}'.format(x_int64, x_int64.dtype))
print('*'*79)
x_float = x.to(torch.float)
print('x_float: {}, type: {}'.format(x_float, x_float.dtype))
x_float16 = x.to(torch.float16)  # float8 does not exist!
print('x_float16: {}, type: {}'.format(x_float16, x_float16.dtype))
x_float32 = x.to(torch.float32)
print('x_float32: {}, type: {}'.format(x_float32, x_float32.dtype))
x_float64 = x.to(torch.float64)
print('x_float64: {}, type: {}'.format(x_float64, x_float64.dtype))
print('*'*79)
x_bool = x.to(torch.bool)
print('x_bool: {}, type: {}'.format(x_bool, x_bool.dtype))
print('*'*79)
x_uint8 = x.to(torch.uint8)
print('x_uint8: {}, type: {}'.format(x_uint8, x_uint8.dtype))

x: tensor([[0.1956, 0.8861, 0.7264, 0.8868],
        [0.1278, 0.0125, 0.1721, 0.5535],
        [0.4012, 0.1849, 0.8640, 0.3388]]), type: torch.float32
x: tensor([[2., 9., 0., 0.],
        [3., 5., 5., 7.],
        [0., 9., 4., 8.]]), type: torch.float32
x: tensor([[2, 8, 1, 6],
        [9, 9, 3, 0],
        [8, 5, 0, 4]], dtype=torch.int32), type: torch.int32
x: tensor([[0.0326, 0.7688, 0.9323, 0.6635],
        [0.1906, 0.7637, 0.9149, 0.3977],
        [0.4180, 0.6731, 0.5643, 0.3347]]), type: torch.float32
x: tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32), type: torch.int32
x: tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]]), type: torch.bool
x: tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]), type: torch.bool
x: tensor([[[False, False],
         [ True,  True],
         [ True,  True],
         [False, False]],

        [[ Tru

In [9]:
# Tensor broadcasting with addition as example. Works for other ops too!
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 3])
ans1 = x1 + x2
print('########## Result 1')
print(x1, '\n+\n', x2, '\n=\n', ans1)

# The three results below (2, 3, 4) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[3, ])
ans2 = x1 + x2
print('########## Result 2')
print(x1, '\n+\n', x2, '\n=\n', ans2)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 3])
ans3 = x1 + x2
print('########## Result 3')
print(x1, '\n+\n', x2, '\n=\n', ans3)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 1, 3])
ans4 = x1 + x2
print('########## Result 4')
print(x1, '\n+\n', x2, '\n=\n', ans4)

# The two results below (5, 6) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 3])
ans5 = x1 + x2
print('########## Result 5')
print(x1, '\n+\n', x2, '\n=\n', ans5)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 2, 3])
ans6 = x1 + x2
print('########## Result 6')
print(x1, '\n+\n', x2, '\n=\n', ans6)

# The two results below (7, 8) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 2, 1])
ans7 = x1 + x2
print('########## Result 7')
print(x1, '\n+\n', x2, '\n=\n', ans7)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 1])
ans8 = x1 + x2
print('########## Result 8')
print(x1, '\n+\n', x2, '\n=\n', ans8)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 1, 1])
ans9 = x1 + x2
print('########## Result 9')
print(x1, '\n+\n', x2, '\n=\n', ans9)

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
# x2 = torch.randint(low=0, high=10, size=[2, ])
# print('########## Result 10')
# print(x1, '\n+\n', x2, '\n=\n', x1+x2)  # This should produce an error.

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 4])
# x2 = torch.randint(low=0, high=10, size=[1, 1, 2])
# print('########## Result 11')
# print(x1, '\n+\n', x2, '\n=\n', x1+x2)  # This should produce an error.

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
# x2 = torch.randint(low=0, high=10, size=[2, ])
# print('########## Result 12')
# print(x1, '\n+\n', x2, '\n=\n', x1+x2)  # This should produce an error.

# noinspection PyTypeChecker
assert (torch.all(ans2==ans3) and torch.all(ans2==ans4))
# noinspection PyTypeChecker
assert torch.all(ans5==ans6)

########## Result 1
tensor([[5, 2, 1],
        [6, 3, 7]]) 
+
 tensor([[7, 9, 8],
        [1, 8, 1]]) 
=
 tensor([[12, 11,  9],
        [ 7, 11,  8]])
########## Result 2
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([8, 7, 2]) 
=
 tensor([[[13,  9,  3],
         [14, 10,  9]],

        [[15, 16, 10],
         [ 9, 15,  3]]])
########## Result 3
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([[8, 7, 2]]) 
=
 tensor([[[13,  9,  3],
         [14, 10,  9]],

        [[15, 16, 10],
         [ 9, 15,  3]]])
########## Result 4
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([[[8, 7, 2]]]) 
=
 tensor([[[13,  9,  3],
         [14, 10,  9]],

        [[15, 16, 10],
         [ 9, 15,  3]]])
########## Result 5
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([[8, 7, 2],
        [0, 6, 2]]) 
=
 tensor([[[13, 

In [10]:
# Some math operations.
x = torch.rand(size=(3, 4))*10  # [0, 10) ranged random floats.
print('x: {}'.format(x))
x_abs = torch.abs(x)
print('abs(x): {}'.format(x_abs))
x_floor = torch.floor(x)
print('floor(x): {}'.format(x_floor))
x_ceil = torch.ceil(x)
print('ceil(x): {}'.format(x_ceil))
x_clamp_bet_3_and_7 = torch.clamp(x, min=3, max=7)
print('x_clamp_bet_3_and_7(x): {}'.format(x_clamp_bet_3_and_7))
x_clamp_below_by_3 = torch.clamp_min(x, min=3)
print('x_clamp_below_by_3(x): {}'.format(x_clamp_below_by_3))
x_clamp_above_by_7 = torch.clamp_max(x, max=7)
print('x_clamp_above_by_7(x): {}'.format(x_clamp_above_by_7))

x: tensor([[4.4509, 3.5929, 7.2038, 0.7305],
        [9.6992, 1.0779, 8.8288, 4.1317],
        [7.5719, 6.9485, 5.2093, 5.9323]])
abs(x): tensor([[4.4509, 3.5929, 7.2038, 0.7305],
        [9.6992, 1.0779, 8.8288, 4.1317],
        [7.5719, 6.9485, 5.2093, 5.9323]])
floor(x): tensor([[4., 3., 7., 0.],
        [9., 1., 8., 4.],
        [7., 6., 5., 5.]])
ceil(x): tensor([[ 5.,  4.,  8.,  1.],
        [10.,  2.,  9.,  5.],
        [ 8.,  7.,  6.,  6.]])
x_clamp_bet_3_and_7(x): tensor([[4.4509, 3.5929, 7.0000, 3.0000],
        [7.0000, 3.0000, 7.0000, 4.1317],
        [7.0000, 6.9485, 5.2093, 5.9323]])
x_clamp_below_by_3(x): tensor([[4.4509, 3.5929, 7.2038, 3.0000],
        [9.6992, 3.0000, 8.8288, 4.1317],
        [7.5719, 6.9485, 5.2093, 5.9323]])
x_clamp_above_by_7(x): tensor([[4.4509, 3.5929, 7.0000, 0.7305],
        [7.0000, 1.0779, 7.0000, 4.1317],
        [7.0000, 6.9485, 5.2093, 5.9323]])


In [11]:
# Comparison operations. Broadcasting is supported
x = torch.randint(low=0, high=2, size=(2, 3))
y = torch.randint(low=0, high=2, size=(2, 3))
print('x: \n{}'.format(x))
print('y: \n{}'.format(y))
print('*'*79)
x_eq_y = torch.eq(input=x, other=y)
print('x==y: \n{}'.format(x_eq_y))
x_less_than_y = torch.less(input=x, other=y)
print('x<y: \n{}'.format(x_less_than_y))
x_less_equal_y = torch.less_equal(input=x, other=y)
print('x<=y: \n{}'.format(x_less_equal_y))
x_greater_than_y = torch.greater(input=x, other=y)
print('x>y: \n{}'.format(x_greater_than_y))
x_greater_equal_y = torch.greater_equal(input=x, other=y)
print('x>=y: \n{}'.format(x_greater_equal_y))

x: 
tensor([[1, 1, 0],
        [0, 1, 0]])
y: 
tensor([[0, 1, 1],
        [0, 0, 1]])
*******************************************************************************
x==y: 
tensor([[False,  True, False],
        [ True, False, False]])
x<y: 
tensor([[False, False,  True],
        [False, False,  True]])
x<=y: 
tensor([[False,  True,  True],
        [ True, False,  True]])
x>y: 
tensor([[ True, False, False],
        [False,  True, False]])
x>=y: 
tensor([[ True,  True, False],
        [ True,  True, False]])


In [12]:
# Reduction operations.
x = torch.randint(low=1, high=6, size=(2, 3))
print('x: \n{}'.format(x))
x_sum = torch.sum(x)
print('sum(x): \n{}'.format(x_sum))
x_mean = torch.mean(x.to(torch.float32))  # `torch.mean` only operates on float and not int/long.
print('mean(x): \n{}'.format(x_mean))
x_product = torch.prod(x)
print('product(x): \n{}'.format(x_product))
x_min = torch.min(x)
print('min(x): \n{}'.format(x_min))
x_max = torch.max(x)
print('max(x): \n{}'.format(x_max))
# Reductions along specific dimensions.
# `keepdim` enables preserving the result shape and thus, is a good practice!
print('*'*79)
x = torch.randint(low=1, high=6, size=(2, 3, 4))
print('x: \n{},\nshape: {}'.format(x, x.shape))
x_sum_dim_0 = torch.sum(x, dim=0, keepdim=True)
print('sum(x): \n{},\nshape: {}'.format(x_sum_dim_0, x_sum_dim_0.shape))
print('*'*79)
x_prod_dim_1 = torch.prod(x, dim=1, keepdim=True)
print('product(x): \n{},\nshape: {}'.format(x_prod_dim_1, x_prod_dim_1.shape))
x_mean_dim_2 = torch.mean(x.float(), dim=2, keepdim=True)  # `torch.mean` operates on floats!
print('mean(x): \n{},\nshape: {}'.format(x_mean_dim_2, x_mean_dim_2.shape))
# The next two results must match the previous two in order!
x_prod_dim_minus2 = torch.prod(x, dim=-2, keepdim=True)  # `torch.mean` operates on floats!
print('product(x): \n{},\nshape: {}'.format(x_prod_dim_minus2, x_prod_dim_minus2.shape))
x_mean_dim_minus1 = torch.mean(x.float(), dim=-1, keepdim=True)
print('mean(x): \n{},\nshape: {}'.format(x_mean_dim_minus1, x_mean_dim_minus1.shape))
# The results with negative dimensions match the standard ones!
print('results with appropriately negated dimensions match: {}'.format(
    torch.all(torch.eq(x_prod_dim_1, x_prod_dim_minus2)) and\
    torch.all(torch.eq(x_mean_dim_2, x_mean_dim_minus1))
))
# Filter unique elements.
print('*'*79)
x = torch.randint(low=0, high=10, size=(4, 3, 2))
print('x: \n{},\nshape: {}'.format(x, x.shape))
x_unique, x_indices, x_counts = torch.unique(
    input=x, sorted=True, return_inverse=True, return_counts=True, dim=None
)
print('unique elements in x: \n{}'.format(x_unique))
print('indices of unique elements in x: \n{}'.format(x_indices))
print('counts of unique elements in x: \n{}'.format(x_counts))
# The "indices" tell to which output index did the current input element was mapped.

x: 
tensor([[1, 1, 5],
        [2, 5, 3]])
sum(x): 
17
mean(x): 
2.8333332538604736
product(x): 
150
min(x): 
1
max(x): 
5
*******************************************************************************
x: 
tensor([[[3, 2, 5, 4],
         [3, 3, 5, 5],
         [3, 4, 1, 3]],

        [[1, 1, 3, 3],
         [1, 3, 4, 3],
         [1, 1, 4, 5]]]),
shape: torch.Size([2, 3, 4])
sum(x): 
tensor([[[4, 3, 8, 7],
         [4, 6, 9, 8],
         [4, 5, 5, 8]]]),
shape: torch.Size([1, 3, 4])
*******************************************************************************
product(x): 
tensor([[[27, 24, 25, 60]],

        [[ 1,  3, 48, 45]]]),
shape: torch.Size([2, 1, 4])
mean(x): 
tensor([[[3.5000],
         [4.0000],
         [2.7500]],

        [[2.0000],
         [2.7500],
         [2.7500]]]),
shape: torch.Size([2, 3, 1])
product(x): 
tensor([[[27, 24, 25, 60]],

        [[ 1,  3, 48, 45]]]),
shape: torch.Size([2, 1, 4])
mean(x): 
tensor([[[3.5000],
         [4.0000],
         [2.7500]],

  

In [13]:
# Vector calculations.
x1 = torch.tensor(data=np.random.randint(low=0, high=5, size=(3, )))
x2 = torch.tensor(data=np.random.randint(low=0, high=5, size=(3, )))
print('x1: {}\nx2: {}'.format(x1, x2))
print('<x1, x2>: {}'.format(torch.dot(input=x1, tensor=x2)))
print('<x1, x2>: {}'.format(torch.vdot(input=x1, other=x2)))
print('x1 X x2: {}'.format(torch.cross(input=x1, other=x2)))  # Behavior with `dim != 3` is weird!
print('i X j: {}, j X i: {}'.format(
    torch.cross(
        input=torch.tensor(data=[1., 0., 0.]),
        other=torch.tensor(data=[0., 1., 0.]),
    ),
    torch.cross(
        input=torch.tensor(data=[0., 1., 0.]),
        other=torch.tensor(data=[1., 0., 0.]),
    )
))  # Right-hand convention: i X j = k. Also, as expected, i X j = -j X i.
# Matrix calculations.
print('*'*79)
m1 = torch.Tensor(size=(2, 3)).normal_()  # torch.Tensor(3, 4) also works. Behaves similarly to `torch.empty`.
m2 = torch.Tensor(size=(3, 2)).normal_()
print('m1: \n{}\nm2: \n{}'.format(m1, m2))
print('m1*m2 = \n{}'.format(torch.matmul(input=m1, other=m2)))
print('m1*m2 = \n{}'.format(torch.mm(input=m1, mat2=m2)))
print('m1 o m2 = \n{}'.format(torch.mul(input=m1, other=m2.T)))  # `.T` transposes.
# Changing dimensions.
m2_transpose = m2.permute(1, 0)
print('m2: \n{}\n(m2)^T: \n{}'.format(m2, m2_transpose))
# Matrix operations on batches of matrices (`torch.matmul` and `@`).
print('*'*79)
x1 = torch.randint(low=0, high=5, size=(4, 2, 3))
x2 = torch.randint(low=0, high=5, size=(4, 3, 2))
print('x1: \n{}\nx2: \n{}'.format(x1, x2))
print('x1 * x2 = \n{}'.format(torch.matmul(input=x1, other=x2)))
for idx in range(4):
    individual_mat_prod = torch.mm(input=x1[idx], mat2=x2[idx])
    calculated_mat_prod = torch.matmul(input=x1, other=x2)[idx]
    print('torch.matmul performs batchwise computation: {}'.format(
        torch.all(
            torch.eq(input=individual_mat_prod, other=calculated_mat_prod)
        )
    ))
print('x1 @ x2 = \n{}'.format(x1@x2))
for idx in range(4):
    individual_mat_prod = torch.mm(input=x1[idx], mat2=x2[idx])
    calculated_mat_prod = (x1@x2)[idx]
    print('torch.matmul performs batchwise computation: {}'.format(
        torch.all(
            torch.eq(input=individual_mat_prod, other=calculated_mat_prod)
        )
    ))

x1: tensor([1, 4, 1])
x2: tensor([4, 2, 2])
<x1, x2>: 14
<x1, x2>: 14
x1 X x2: tensor([  6,   2, -14])
i X j: tensor([0., 0., 1.]), j X i: tensor([ 0.,  0., -1.])
*******************************************************************************
m1: 
tensor([[ 0.3296, -0.8763, -1.6768],
        [-0.7247,  0.9634,  0.1342]])
m2: 
tensor([[ 0.5485,  2.1349],
        [-0.8782, -2.0826],
        [ 1.8317, -0.5535]])
m1*m2 = 
tensor([[-2.1211,  3.4569],
        [-0.9977, -3.6278]])
m1*m2 = 
tensor([[-2.1211,  3.4569],
        [-0.9977, -3.6278]])
m1 o m2 = 
tensor([[ 0.1808,  0.7695, -3.0714],
        [-1.5471, -2.0064, -0.0743]])
m2: 
tensor([[ 0.5485,  2.1349],
        [-0.8782, -2.0826],
        [ 1.8317, -0.5535]])
(m2)^T: 
tensor([[ 0.5485, -0.8782,  1.8317],
        [ 2.1349, -2.0826, -0.5535]])
*******************************************************************************
x1: 
tensor([[[0, 4, 4],
         [3, 2, 3]],

        [[1, 1, 4],
         [4, 3, 0]],

        [[3, 0, 0],
      

In [14]:
# Linear algebra.
x = torch.tensor(data=[[3, 2], [4, 3]]).float()
# Determinant.
print('determinant(\n', x, '\n) = ', torch.det(x))
# Eigenpairs.
print('*'*79)
print('eigenpair(\n', x, '\n) = ', torch.eig(input=x, eigenvectors=True))
print('eigenvalues: \n{}\nshape: \n{}'.format(
    torch.eig(input=x, eigenvectors=True)[0],
    torch.eig(input=x, eigenvectors=True)[0].shape
))
print('eigenvectors: \n{}\nshape: \n{}'.format(
    torch.eig(input=x, eigenvectors=True)[1],
    torch.eig(input=x, eigenvectors=True)[1].shape
))
lambdas, xs = torch.eig(input=x, eigenvectors=True)
lambda_1, lambda_2 = lambdas[0, 0], lambdas[1, 0]
x_1, x_2 = xs[:, 0].view(-1, 1), xs[:, 1].view(-1, 1)
print('error(A*x_1, lambda_1*x_1): \n{}'.format(
    torch.dist(torch.mm(input=x, mat2=x_1), lambda_1*x_1)
))
print('error(A*x_2, lambda_2*x_2): \n{}'.format(
    torch.dist(torch.mm(input=x, mat2=x_2), lambda_2*x_2)
))
# Singular value decomposition of a single matrix.
print('*'*79)
x = torch.rand(3, 2)  # SVD of a single matrix
print('svd(\n', x, '\n) = ', torch.linalg.svd(x, full_matrices=False))
u, s, v_transpose = torch.linalg.svd(x, full_matrices=False)
print('x.shape:', x.shape, 'U.shape:', u.shape, 'S.shape:', s.shape, 'V.shape:', v_transpose.shape)
print('U*S*V^T = ', u @ torch.diag_embed(s) @ v_transpose)
print('U*S*V^T = ', torch.mm(torch.mm(u, torch.diag(s)), v_transpose))
print('error(x, U*S*V^T) = ', torch.dist(torch.mm(torch.mm(u, torch.diag(s)), v_transpose), x))
# Singular value decomposition of a batch of matrices.
print('*'*79)
x = torch.rand(4, 3, 2)  # SVD of a batch of matrices
print('svd(\n', x, '\n) = ', torch.linalg.svd(x, full_matrices=False))
u, s, v_transpose = torch.linalg.svd(x, full_matrices=False)
print('x.shape:', x.shape, 'U.shape:', u.shape, 'S.shape:', s.shape, 'V.shape:', v_transpose.shape)
print('U*S*V^T = ', u @ torch.diag_embed(s) @ v_transpose)
"""
@ performs ([m, n], [n, p] -> [m, p]) matrix multiplications on [<dims>, m, n]
and [<dims>, n, p] tensors to produces [<dims>, m, p] output.
diag_embed changes a [<dims>, n] dimensional array into [<dims>, n, n] tensor
with nxn diagonal matrices for each of the rows.
"""
print('error(x, U*S*V^T) = ', torch.dist(u @ torch.diag_embed(s) @ v_transpose, x))

determinant(
 tensor([[3., 2.],
        [4., 3.]]) 
) =  tensor(1.)
*******************************************************************************
eigenpair(
 tensor([[3., 2.],
        [4., 3.]]) 
) =  torch.return_types.eig(
eigenvalues=tensor([[5.8284, 0.0000],
        [0.1716, 0.0000]]),
eigenvectors=tensor([[ 0.5774, -0.5774],
        [ 0.8165,  0.8165]]))
eigenvalues: 
tensor([[5.8284, 0.0000],
        [0.1716, 0.0000]])
shape: 
torch.Size([2, 2])
eigenvectors: 
tensor([[ 0.5774, -0.5774],
        [ 0.8165,  0.8165]])
shape: 
torch.Size([2, 2])
error(A*x_1, lambda_1*x_1): 
2.384185791015625e-07
error(A*x_2, lambda_2*x_2): 
1.4901161193847656e-07
*******************************************************************************
svd(
 tensor([[0.7189, 0.0897],
        [0.3745, 0.2345],
        [0.8760, 0.5965]]) 
) =  torch.return_types.linalg_svd(
U=tensor([[-0.5141,  0.8564],
        [-0.3313, -0.1469],
        [-0.7911, -0.4950]]),
S=tensor([1.3279, 0.2830]),
V=tensor([[-0.8937, -0

In [15]:
# In-place tensor operations.
x1 = torch.tensor(data=[1.0, 2.0, 3.0])
x2 = torch.tensor(data=[4.0, 5.0, 6.0])
print('*'*79)
print('x1 + x2: \n{}'.format(torch.add(input=x1, other=x1)))
print('x1: \n{}\nx2: \n{}'.format(x1, x2))
#
x1 = torch.tensor(data=[1.0, 2.0, 3.0])
x2 = torch.tensor(data=[4.0, 5.0, 6.0])
print('*'*79)
print('x1 + x2: \n{}'.format(x1.add_(x2)))
print('x1: \n{}\nx2: \n{}'.format(x1, x2))
#
x1 = torch.tensor(data=[1.0, 2.0, 3.0])
x2 = torch.tensor(data=[4.0, 5.0, 6.0])
print('*'*79)
print('x1 - x2: \n{}'.format(x1.sub_(x2)))
print('x1: \n{}\nx2: \n{}'.format(x1, x2))
#
x1 = torch.tensor(data=[1.0, 2.0, 3.0])
x2 = torch.tensor(data=[4.0, 5.0, 6.0])
print('*'*79)
print('x1 o x2: \n{}'.format(x1.mul_(x2)))
print('x1: \n{}\nx2: \n{}'.format(x1, x2))
#
x1 = torch.tensor(data=[1.0, 2.0, 3.0])
x2 = torch.tensor(data=[4.0, 5.0, 6.0])
print('*'*79)
print('x1 / x2: \n{}'.format(x1.div_(x2)))
print('x1: \n{}\nx2: \n{}'.format(x1, x2))
#
x1 = torch.tensor(data=[1.0, 2.0, 3.0])
x2 = torch.tensor(data=[4.0, 5.0, 6.0])
print('*'*79)
print('sin(x1): \n{}'.format(x1.sin_()))
print('arccos(x2/6): \n{}'.format(x2.div_(6).arccos_()))
print('x1: \n{}\nx2: \n{}'.format(x1, x2))
# Set operation outputs to existing tensor memory locations.
x1 = torch.tensor([[1.0, 2.0], [3.0, 4]])
x2 = torch.tensor([[1.0, 2.0], [3.0, 5.0]])
print('*'*79)
x_out_1 = torch.Tensor(2, 2)
x_out_2 = torch.Tensor(3, )
out_id_1 = id(x_out_1)
out_id_2 = id(x_out_2)
print('x_out_1: \n{}\nid: \n{}'.format(x_out_1, out_id_1))  # Should hold garbage!
print('x_out_2: \n{}\nid: \n{}'.format(x_out_2, out_id_2))  # Should hold garbage!
x3 = torch.add(input=x1, other=x2, out=x_out_1)  # x3 and x_out_1 are now the SAME OBJECTS (just different identifiers)!
print('x3: \n{}\nx_out_1: \n{}'.format(x3, x_out_1))
print('x3 is the same object as x_out_1: {}'.format(x3 is x_out_1))
print('id(x3): {}, id(x_out_1): {}'.format(id(x3), out_id_1))
print('x3 and x_out_1 ids are the same: {}'.format(id(x3) == out_id_1))
# If dimensions of the original do not match, they are updated!
x4 = torch.mean(input=x2, dim=0, keepdim=True, out=x_out_2)  # output has two dimensions but `x_out_2` had only 1!
print('x4: \n{}\nx_out_2: \n{}'.format(x4, x_out_2))
print('x4 is the same object as x_out_2: {}'.format(x4 is x_out_2))
print('id(x4): {}, id(x_out_2): {}'.format(id(x4), out_id_2))
print('x4 and x_out_2 ids are the same: {}'.format(id(x4) == out_id_2))

*******************************************************************************
x1 + x2: 
tensor([2., 4., 6.])
x1: 
tensor([1., 2., 3.])
x2: 
tensor([4., 5., 6.])
*******************************************************************************
x1 + x2: 
tensor([5., 7., 9.])
x1: 
tensor([5., 7., 9.])
x2: 
tensor([4., 5., 6.])
*******************************************************************************
x1 - x2: 
tensor([-3., -3., -3.])
x1: 
tensor([-3., -3., -3.])
x2: 
tensor([4., 5., 6.])
*******************************************************************************
x1 o x2: 
tensor([ 4., 10., 18.])
x1: 
tensor([ 4., 10., 18.])
x2: 
tensor([4., 5., 6.])
*******************************************************************************
x1 / x2: 
tensor([0.2500, 0.4000, 0.5000])
x1: 
tensor([0.2500, 0.4000, 0.5000])
x2: 
tensor([4., 5., 6.])
*******************************************************************************
sin(x1): 
tensor([0.8415, 0.9093, 0.1411])
arccos(x2/6): 
tensor([0.8

In [37]:
# Slicing.
x = torch.randint(low=0, high=5, size=(3, 2, 5, 4))  # `x` has 3 tensors of size (2, 4), each of which has 2 of size (4, ).
print('x: \n{}'.format(x))
print('x[0]: \n{}'.format(x[0]))
print('x[0, 1]: \n{}'.format(x[0, 1]))
print('x[0][1]: \n{}'.format(x[0][1]))
print('x[0, 1] == x[0][1]: \n{}'.format(
    torch.all(torch.eq(input=x[0][1], other=x[0, 1]))
))
idx1, idx2, idx3 = \
    np.random.randint(low=0, high=3),\
    np.random.randint(low=0, high=2),\
    np.random.randint(low=0, high=5)
print('x[{}][{}][{}] == x[{},{},{}]: \n{}'.format(
    idx1, idx2, idx3, idx1, idx2, idx3,
    torch.all(torch.eq(input=x[idx1][idx2][idx3], other=x[idx1, idx2, idx3]))
))
print('x[{}][{}][{}] == x[{}][{},{}]: \n{}'.format(
    idx1, idx2, idx3, idx1, idx2, idx3,
    torch.all(torch.eq(input=x[idx1][idx2][idx3], other=x[idx1][idx2, idx3]))
))
print('x[{}][{}][{}] == x[{},{}][{}]: \n{}'.format(
    idx1, idx2, idx3, idx1, idx2, idx3,
    torch.all(torch.eq(input=x[idx1][idx2][idx3], other=x[idx1, idx2][idx3]))
))
# Assigning tensors.
print('*'*79)
x = torch.Tensor(2, 2).normal_()
y = x
print('x: \n{}'.format(x))
print('y: \n{}'.format(y))
print('x is y: {}'.format(x is y))  # True: assignment creates a label for the tensor.
print('x[0][0]: {}'.format(x[0][0]))
y[0][0] = 1000.0
print('x[0][0]: {}'.format(x[0][0]))  # Gets updated as x is y.
# Cloning tensors.
print('*'*79)
x = torch.Tensor(2, 2).normal_()
z = x.clone()  # If `x` had autograd enabled, then so will be the case with `z`.
print('x: \n{}'.format(x))
print('z: \n{}'.format(z))
print('x is z: {}'.format(x is z))  # False. Clone create a copy of the tensor.
print('x[0][0]: {}'.format(x[0][0]))
z[0][0] = 1000.0
print('x[0][0]: {}'.format(x[0][0]))  # DOESN'T GET updated as x is not z.
# Cloning tensors without requiring gradient.
print('*'*79)
x = torch.Tensor(2, 2).normal_().requires_grad_()
u = x.clone()  # Tracks the history of `x` in order to backprop gradients.
v = x.detach().clone()  # DOESN'T TRACK the history of `x`
print('x: \n{}'.format(x))
print('u: \n{}'.format(u))
print('v: \n{}'.format(v))

x: 
tensor([[[[1, 2, 1, 2],
          [0, 0, 4, 3],
          [0, 3, 2, 3],
          [0, 3, 0, 4],
          [3, 3, 3, 0]],

         [[1, 0, 0, 0],
          [4, 0, 0, 0],
          [0, 3, 3, 2],
          [2, 1, 3, 4],
          [2, 1, 1, 4]]],


        [[[2, 3, 1, 2],
          [3, 1, 3, 3],
          [2, 0, 1, 2],
          [2, 4, 0, 0],
          [0, 3, 3, 2]],

         [[0, 4, 3, 0],
          [4, 3, 4, 2],
          [0, 4, 2, 2],
          [1, 1, 4, 2],
          [1, 2, 3, 3]]],


        [[[4, 0, 4, 2],
          [3, 1, 3, 3],
          [4, 3, 3, 2],
          [3, 1, 1, 4],
          [3, 1, 1, 2]],

         [[2, 2, 3, 4],
          [4, 2, 1, 1],
          [2, 2, 2, 3],
          [2, 1, 4, 1],
          [4, 3, 2, 1]]]])
x[0]: 
tensor([[[1, 2, 1, 2],
         [0, 0, 4, 3],
         [0, 3, 2, 3],
         [0, 3, 0, 4],
         [3, 3, 3, 0]],

        [[1, 0, 0, 0],
         [4, 0, 0, 0],
         [0, 3, 3, 2],
         [2, 1, 3, 4],
         [2, 1, 1, 4]]])
x[0, 1]: 
tensor([

In [50]:
# GPU-compatibility.
print('is GPU available: \n{}'.format(torch.cuda.is_available()))
# Setting tensors to GPU.
x = torch.tensor(data=([2, 3], (4, 2)))
x = x.cuda() if torch.cuda.is_available() else x
print('x: \n{}'.format(x))
# Alternate method.
if torch.cuda.is_available():
    x = torch.Tensor(2, 2, device='cuda')
else:
    x = torch.Tensor(2, 2)
print('x: \n{}'.format(x))
try:
    print('trying to set x on gpu: \n{}'.format(torch.Tensor(2, 3, device='cuda').normal_()))
except Exception as e:
    print('Exception: {}'.format(e))
# Devices in pytorch.
device = torch.device('cpu')  # `torch.device('cuda')` for GPUs.
print('number of GPU devices: {}'.format(torch.cuda.device_count()))
# If more than one GPUs, say `n`, mention `torch.device('cuda:<i>')` for `0 <= i < n`.
# Moving tensor to a specific device.
my_device = torch.device('cpu')
x = torch.tensor(data=((1, 2), (3, 4))).float()
x = x.to(my_device)
print('x: \n{}\nis x on GPU: {}'.format(x, x.is_cuda))

is GPU available: 
False
x: 
tensor([[2, 3],
        [4, 2]])
x: 
tensor([[2.6101e+20, 1.0415e-11],
        [1.0621e-05, 1.3297e+22]])
Exception: legacy constructor expects device type: cpubut device type: cuda was passed
number of GPU devices: 0
x: 
tensor([[1., 2.],
        [3., 4.]])
is x on GPU: False


In [96]:
# Adding a dimension to a tensor at a particular location.
x = torch.Tensor(3, 2, 4, 5).normal_()
print('x.shape: {}'.format(x.shape))
y = x.unsqueeze(dim=1)  # w.r.t. original tensor, add a dimension at index 1. SHAPE: [3, 1, 2, 4, 5].
print('x.unsqueeze(dim=1).shape: {}'.format(y.shape))
z1 = y.unsqueeze(dim=1)
print('y.unsqueeze(dim=1).shape: {}'.format(z1.shape))
z2 = y.unsqueeze(dim=2)
print('y.unsqueeze(dim=2).shape: {}'.format(z2.shape))
x_squeezed = z1.unsqueeze(dim=-1).squeeze()  # Removes ALL dimensions with size 1.
print('x_squeezed.shape: {}'.format(x_squeezed.shape))
x_squeezed_dim_1 = z2.squeeze(dim=2)
print('x_squeezed_dim_1.shape: {}'.format(x_squeezed_dim_1.shape))  # SHAPE: [3, 1, 2, 4, 5].
# `.squeeze(<...>)` works only when dimension is 1 along some index.
# Re-orienting a tensor by changing the order of axes.
print('*'*79)
x = torch.Tensor(64, 3, 28, 28).normal_()
print('x.shape: {}'.format(x.shape))
x_channel_first = x.permute(1, 0, 2, 3)
print('x_channel_first.shape: {}'.format(x_channel_first.shape))
idx1 = np.random.randint(low=0, high=64)
idx2 = np.random.randint(low=0, high=3)
print('x_channel_first[{},{}] == x[{},{}]: {}'.format(
    idx2, idx1, idx1, idx2,
    torch.all(torch.eq(input=x[idx1, idx2], other=x_channel_first[idx2, idx1]))
))
x_height_first = x.permute(2, 0, 1, 3)
print('x_height_first.shape: {}'.format(x_height_first.shape))
idx1 = np.random.randint(low=0, high=64)
idx2 = np.random.randint(low=0, high=3)
idx3 = np.random.randint(low=0, high=28)
print('x[{},{},{}] == x_height_first[{},{},{}]: {}'.format(
    idx1, idx2, idx3, idx3, idx1, idx2,
    torch.all(torch.eq(input=x[idx1, idx2, idx3], other=x_height_first[idx3, idx1, idx2]))
))
# Flatten out tensors.
print('*'*79)
x_2d_batched = torch.Tensor(64, 3, np.random.randint(0, 10), np.random.randint(0, 10)).normal_()
print('x_2d_batched.shape: {}'.format(x_2d_batched.shape))
B = x_2d_batched.shape[0]
x_flattened_batched = x_2d_batched.view(B, -1)  # Whenever UNAMBIGUOUS, the missing dimension given by `-1` is evaluated.
print('x_flattened_batched.shape: {}'.format(x_flattened_batched.shape))
print('{} == {}: {}'.format(
    '*'.join([str(dim) for dim in x_2d_batched.shape[1: ]]),
    np.prod(np.array([dim for dim in x_2d_batched.shape[1: ]])),
    np.prod(np.array([dim for dim in x_2d_batched.shape[1: ]]))==x_flattened_batched.shape[-1]
))
# Properties of viewing. `.view(<...>)` returns A NEW TENSOR with same data and given shape.
print('*'*79)
x = torch.randint(low=0, high=10, size=(3, 2, 4))
y = x.view(-1)
print('x: \n{}'.format(x))
print('y: \n{}'.format(y))
print('x is y: {}'.format(x is y))
z1 = x.reshape(-1)
z2 = x.view(-1)
print('x: \n{}'.format(x))
print('z1: \n{}'.format(z1))
print('z2: \n{}'.format(z2))
print('x is z1: {}'.format(x is z1))
print('z1 == z2: {}'.format(
    torch.all(torch.eq(input=z1, other=z2))
))
# In place squeeze and unsqueeze.
print('*'*79)
x = torch.Tensor(3, 2, 4, 5).normal_()
print('x.shape: {}'.format(x.shape))
x.unsqueeze_(dim=-1)
print('x.shape: {}'.format(x.shape))  # Shape is changed in place.
x.unsqueeze_(dim=2)
print('x.shape: {}'.format(x.shape))  # Shape is changed in place.
x.squeeze_()
print('x.shape: {}'.format(x.shape))  # Shape is changed in place.
x.unsqueeze_(dim=-1)
print('x.shape: {}'.format(x.shape))  # Shape is changed in place.
x.unsqueeze_(dim=2)
print('x.shape: {}'.format(x.shape))  # Shape is changed in place.
x.squeeze_(dim=5)  # Squeeze out the last dimension.
print('x.shape: {}'.format(x.shape))  # Shape is changed in place.
x.squeeze_(dim=-3)  # Squeeze out the third dimension (index `2`)
print('x.shape: {}'.format(x.shape))  # Shape is changed in place.
# Intrusive shape changes.
print('*'*79)
x = torch.randint(low=0, high=10, size=(3, 4))
print('x: \n{}'.format(x))
x.resize_(2, 3)  # Takes first 6 elements from `x` and arranges them in shape `(2, 3)`.
print('x resized in place: \n{}'.format(x))
y = torch.randint(low=0, high=10, size=(3, 4))
print('y: \n{}'.format(y))
y.resize_(4, 5)  # Takes first 3*4=12 elements from `y` and appends garbage to make `(4, 5)` shaped tensor.
print('y resized in place: \n{}'.format(y))

x.shape: torch.Size([3, 2, 4, 5])
x.unsqueeze(dim=1).shape: torch.Size([3, 1, 2, 4, 5])
y.unsqueeze(dim=1).shape: torch.Size([3, 1, 1, 2, 4, 5])
y.unsqueeze(dim=2).shape: torch.Size([3, 1, 1, 2, 4, 5])
x_squeezed.shape: torch.Size([3, 2, 4, 5])
x_squeezed_dim_1.shape: torch.Size([3, 1, 2, 4, 5])
*******************************************************************************
x.shape: torch.Size([64, 3, 28, 28])
x_channel_first.shape: torch.Size([3, 64, 28, 28])
x_channel_first[0,5] == x[5,0]: True
x_height_first.shape: torch.Size([28, 64, 3, 28])
x[38,1,26] == x_height_first[26,38,1]: True
*******************************************************************************
x_2d_batched.shape: torch.Size([64, 3, 2, 2])
x_flattened_batched.shape: torch.Size([64, 12])
3*2*2 == 12: True
*******************************************************************************
x: 
tensor([[[8, 7, 7, 1],
         [7, 6, 8, 7]],

        [[6, 2, 7, 8],
         [4, 8, 9, 5]],

        [[9, 5, 0, 9],
         

In [108]:
# To-and-from numpy.
x_np = np.random.randint(low=0, high=10, size=(3, 4))
print('x_np: \n{}\nx_np type: {}'.format(x_np, x_np.dtype))
x_torch = torch.from_numpy(x_np)  # This preserves the type.
print('x_torch: \n{}\nx_torch type: {}'.format(x_torch, x_torch.dtype))
x_np[0, 0] = 1000
print('x_np: \n{}\nx_torch: \n{}'.format(x_np, x_torch))  # They share the same underlying memory!
x_torch[-1, -1] = 2000
print('x_np: \n{}\nx_torch: \n{}'.format(x_np, x_torch))  # They share the same underlying memory!
print('*'*79)
x_torch = torch.tensor(data=((1, 2,), (3, 4)), dtype=torch.float32)
x_np = x_torch.numpy()
print('x_torch: \n{}\nx_torch type: {}'.format(x_torch, x_torch.dtype))
print('x_np: \n{}\nx_np type: {}'.format(x_np, x_np.dtype))
x_np[0, 0] = 1000
print('x_np: \n{}\nx_torch: \n{}'.format(x_np, x_torch))  # They share the same underlying memory!
x_torch[-1, -1] = 2000
print('x_np: \n{}\nx_torch: \n{}'.format(x_np, x_torch))  # They share the same underlying memory!
# If we want to change the data locations, use `.clone()`
print('*'*79)
x_np = np.random.randint(low=0, high=10, size=(3, 4))
print('x_np: \n{}\nx_np type: {}'.format(x_np, x_np.dtype))
x_torch = torch.from_numpy(x_np).clone()  # This preserves the type.
print('x_torch: \n{}\nx_torch type: {}'.format(x_torch, x_torch.dtype))
x_np[0, 0] = 1000
print('x_np: \n{}\nx_torch: \n{}'.format(x_np, x_torch))  # They DO NOT share the same underlying memory!
x_torch[-1, -1] = 2000
print('x_np: \n{}\nx_torch: \n{}'.format(x_np, x_torch))  # They DO NOT share the same underlying memory!
print('*'*79)
x_torch = torch.tensor(data=((1, 2,), (3, 4)), dtype=torch.float32)
x_np = x_torch.clone().numpy()
print('x_torch: \n{}\nx_torch type: {}'.format(x_torch, x_torch.dtype))
print('x_np: \n{}\nx_np type: {}'.format(x_np, x_np.dtype))
x_np[0, 0] = 1000
print('x_np: \n{}\nx_torch: \n{}'.format(x_np, x_torch))  # They share the same underlying memory!
x_torch[-1, -1] = 2000
print('x_np: \n{}\nx_torch: \n{}'.format(x_np, x_torch))  # They share the same underlying memory!

x_np: 
[[7 8 4 2]
 [6 5 3 6]
 [5 3 8 7]]
x_np type: int64
x_torch: 
tensor([[7, 8, 4, 2],
        [6, 5, 3, 6],
        [5, 3, 8, 7]])
x_torch type: torch.int64
x_np: 
[[1000    8    4    2]
 [   6    5    3    6]
 [   5    3    8    7]]
x_torch: 
tensor([[1000,    8,    4,    2],
        [   6,    5,    3,    6],
        [   5,    3,    8,    7]])
x_np: 
[[1000    8    4    2]
 [   6    5    3    6]
 [   5    3    8 2000]]
x_torch: 
tensor([[1000,    8,    4,    2],
        [   6,    5,    3,    6],
        [   5,    3,    8, 2000]])
*******************************************************************************
x_torch: 
tensor([[1., 2.],
        [3., 4.]])
x_torch type: torch.float32
x_np: 
[[1. 2.]
 [3. 4.]]
x_np type: float32
x_np: 
[[1000.    2.]
 [   3.    4.]]
x_torch: 
tensor([[1000.,    2.],
        [   3.,    4.]])
x_np: 
[[1000.    2.]
 [   3. 2000.]]
x_torch: 
tensor([[1000.,    2.],
        [   3., 2000.]])
*****************************************************************