In [95]:
# Dependencies
import torch

In [96]:
# Initializing tensors-- zeros
zeros = torch.zeros(2, 3)
print(zeros)
print(zeros.dtype)

zeros_int = torch.zeros(2, 3, dtype=torch.int32)
print(zeros_int)
print(zeros_int.dtype)

zeros_int_another = torch.zeros(2, 3).int()
print(zeros_int_another)
print(zeros_int_another.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.int32
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.int32


In [97]:
# Data types

In [98]:
# Initializing tensors-- ones
ones = torch.ones(2, 3).int()
print(ones)
print(ones.dtype)


tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.int32


In [99]:
# Initializing booleans
bools = torch.randint(low=0, high=2, size=[2, 3], dtype=torch.bool)
print(bools)
print(bools.dtype)
bools_another = torch.randint(low=0, high=2, size=[2, 3])

print(bools_another)
print(bools_another.dtype)  # int64
bools_another = bools_another.bool()
print(bools_another)
print(bools_another.dtype)

tensor([[False, False, False],
        [False,  True, False]])
torch.bool
tensor([[0, 0, 1],
        [1, 0, 0]])
torch.int64
tensor([[False, False,  True],
        [ True, False, False]])
torch.bool


In [100]:
# Initializing random float tensors
torch.manual_seed(seed=7)  # Seeding for reproducibility
random_1 = torch.rand(2, 3)
random_2 = torch.rand(2, 3)

torch.manual_seed(seed=7)
random_1_again = torch.rand(2, 3)
random_2_again = torch.rand(2, 3)
print(random_1)
print(random_1_again)
print(random_2)
print(random_2_again)

tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251]])
tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251]])
tensor([[0.2071, 0.6297, 0.3653],
        [0.8513, 0.8549, 0.5509]])
tensor([[0.2071, 0.6297, 0.3653],
        [0.8513, 0.8549, 0.5509]])


In [105]:
# Addition and casting
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 3])
ans1 = x1 + x2
print('########## Result 1')
print(x1, '\n+\n', x2, '\n=\n', ans1)

# The three results below (2, 3, 4) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[3, ])
ans2 = x1 + x2
print('########## Result 2')
print(x1, '\n+\n', x2, '\n=\n', ans2)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 3])
ans3 = x1 + x2
print('########## Result 3')
print(x1, '\n+\n', x2, '\n=\n', ans3)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 1, 3])
ans4 = x1 + x2
print('########## Result 4')
print(x1, '\n+\n', x2, '\n=\n', ans4)

# The two results below (5, 6) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 3])
ans5 = x1 + x2
print('########## Result 5')
print(x1, '\n+\n', x2, '\n=\n', ans5)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 2, 3])
ans6 = x1 + x2
print('########## Result 6')
print(x1, '\n+\n', x2, '\n=\n', ans6)

# The two results below (7, 8) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 2, 1])
ans7 = x1 + x2
print('########## Result 7')
print(x1, '\n+\n', x2, '\n=\n', ans7)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 1])
ans8 = x1 + x2
print('########## Result 8')
print(x1, '\n+\n', x2, '\n=\n', ans8)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 1, 1])
ans9 = x1 + x2
print('########## Result 9')
print(x1, '\n+\n', x2, '\n=\n', ans9)

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
# x2 = torch.randint(low=0, high=10, size=[2, ])
# print('########## Result 10')
# print(x1, '\n+\n', x2, '\n=\n', x1+x2)  # This should produce an error.

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 4])
# x2 = torch.randint(low=0, high=10, size=[1, 1, 2])
# print('########## Result 11')
# print(x1, '\n+\n', x2, '\n=\n', x1+x2)  # This should produce an error.

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
# x2 = torch.randint(low=0, high=10, size=[2, ])
# print('########## Result 12')
# print(x1, '\n+\n', x2, '\n=\n', x1+x2)  # This should produce an error.

# noinspection PyTypeChecker
assert (torch.all(ans2==ans3) and torch.all(ans2==ans4))
# noinspection PyTypeChecker
assert torch.all(ans5==ans6)

########## Result 1
tensor([[5, 2, 1],
        [6, 3, 7]]) 
+
 tensor([[7, 9, 8],
        [1, 8, 1]]) 
=
 tensor([[12, 11,  9],
        [ 7, 11,  8]])
########## Result 2
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([8, 7, 2]) 
=
 tensor([[[13,  9,  3],
         [14, 10,  9]],

        [[15, 16, 10],
         [ 9, 15,  3]]])
########## Result 3
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([[8, 7, 2]]) 
=
 tensor([[[13,  9,  3],
         [14, 10,  9]],

        [[15, 16, 10],
         [ 9, 15,  3]]])
########## Result 4
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([[[8, 7, 2]]]) 
=
 tensor([[[13,  9,  3],
         [14, 10,  9]],

        [[15, 16, 10],
         [ 9, 15,  3]]])
########## Result 5
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([[8, 7, 2],
        [0, 6, 2]]) 
=
 tensor([[[13, 

In [106]:
# Other math operations behave similarly
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 3])
print('########## Result 1')
ans1 = x1 * x2
print(x1, '\n*\n', x2, '\n=\n', ans1)

# The three results below (2, 3, 4) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[3, ])
print('########## Result 2')
ans2 = x1 * x2
print(x1, '\n*\n', x2, '\n=\n', ans2)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 3])
print('########## Result 3')
ans3 = x1 * x2
print(x1, '\n*\n', x2, '\n=\n', ans3)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 1, 3])
print('########## Result 4')
ans4 = x1 * x2
print(x1, '\n*\n', x2, '\n=\n', ans4)

# The two results below (5, 6) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 3])
print('########## Result 5')
ans5 = x1 * x2
print(x1, '\n*\n', x2, '\n=\n', ans5)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 2, 3])
print('########## Result 6')
ans6 = x1 * x2
print(x1, '\n*\n', x2, '\n=\n', ans6)

# The two results below (7, 8) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 2, 1])
print('########## Result 7')
ans7 = x1 * x2
print(x1, '\n*\n', x2, '\n=\n', ans7)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 1])
print('########## Result 8')
ans8 = x1 * x2
print(x1, '\n*\n', x2, '\n=\n', ans8)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 1, 1])
print('########## Result 9')
ans9 = x1 * x2
print(x1, '\n*\n', x2, '\n=\n', ans9)

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
# x2 = torch.randint(low=0, high=10, size=[2, ])
# print('########## Result 10')
# print(x1, '\n*\n', x2, '\n=\n', x1*x2)  # This should produce an error.

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 4])
# x2 = torch.randint(low=0, high=10, size=[1, 1, 2])
# print('########## Result 11')
# print(x1, '\n*\n', x2, '\n=\n', x1*x2)  # This should produce an error.

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
# x2 = torch.randint(low=0, high=10, size=[2, ])
# print('########## Result 12')
# print(x1, '\n*\n', x2, '\n=\n', x1*x2)  # This should produce an error.

# noinspection PyTypeChecker
assert (torch.all(ans2==ans3) and torch.all(ans2==ans4))
# noinspection PyTypeChecker
assert torch.all(ans5==ans6)

########## Result 1
tensor([[5, 2, 1],
        [6, 3, 7]]) 
*
 tensor([[7, 9, 8],
        [1, 8, 1]]) 
=
 tensor([[35, 18,  8],
        [ 6, 24,  7]])
########## Result 2
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
*
 tensor([8, 7, 2]) 
=
 tensor([[[40, 14,  2],
         [48, 21, 14]],

        [[56, 63, 16],
         [ 8, 56,  2]]])
########## Result 3
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
*
 tensor([[8, 7, 2]]) 
=
 tensor([[[40, 14,  2],
         [48, 21, 14]],

        [[56, 63, 16],
         [ 8, 56,  2]]])
########## Result 4
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
*
 tensor([[[8, 7, 2]]]) 
=
 tensor([[[40, 14,  2],
         [48, 21, 14]],

        [[56, 63, 16],
         [ 8, 56,  2]]])
########## Result 5
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
*
 tensor([[8, 7, 2],
        [0, 6, 2]]) 
=
 tensor([[[40, 

In [124]:
# Advanced operations. Certain operations are only on floats.
torch.manual_seed(seed=7)
x = torch.randint(low=0, high=10, size=[2, 3], dtype=torch.float32)

print('min(\n', x, '\n) = ', torch.min(x))
print('*'*79)

print('max(\n', x, '\n) = ', torch.max(x))
print('*'*79)

print('mean(\n', x, '\n) = ', torch.mean(x))
print('*'*79)

print('std(\n', x, '\n) = ', torch.std(x))
print('*'*79)

print('mean_and_std(\n', x, '\n) = ', torch.std_mean(x))  # Returns the std and mean as tensors in a tuple.
print('*'*79)

torch.manual_seed(seed=7)
x = torch.randint(low=0, high=10, size=[2, 3, 4], dtype=torch.float32)

# In case multiple indices for match of min/max, the first index of a match is returned.
print('min_along_dim_0(\n', x, '\n) = ', torch.min(x, dim=0, keepdim=True)[0])
print('min_along_dim_0_indices(\n', x, '\n) = ', torch.min(x, dim=0, keepdim=True)[1])
print('*'*79)

print('max_along_dim_1(\n', x, '\n) = ', torch.max(x, dim=1, keepdim=True)[0])
print('max_along_dim_1_indices(\n', x, '\n) = ', torch.max(x, dim=1, keepdim=True)[1])
print('*'*79)

print('max_along_dim_2(\n', x, '\n) = ', torch.max(x, dim=2, keepdim=True)[0])
print('max_along_dim_2_indices(\n', x, '\n) = ', torch.max(x, dim=2, keepdim=True)[1])
print('*'*79)


min(
 tensor([[5., 2., 1.],
        [6., 3., 7.]]) 
) =  tensor(1.)
*******************************************************************************
max(
 tensor([[5., 2., 1.],
        [6., 3., 7.]]) 
) =  tensor(7.)
*******************************************************************************
mean(
 tensor([[5., 2., 1.],
        [6., 3., 7.]]) 
) =  tensor(4.)
*******************************************************************************
std(
 tensor([[5., 2., 1.],
        [6., 3., 7.]]) 
) =  tensor(2.3664)
*******************************************************************************
mean_and_std(
 tensor([[5., 2., 1.],
        [6., 3., 7.]]) 
) =  (tensor(2.3664), tensor(4.))
*******************************************************************************
min_along_dim_0(
 tensor([[[5., 2., 1., 6.],
         [3., 7., 7., 9.],
         [8., 1., 8., 1.]],

        [[8., 7., 2., 0.],
         [6., 2., 3., 8.],
         [6., 0., 5., 1.]]]) 
) =  tensor([[[5., 2., 1., 0.],
         [3

In [132]:
# Other mathematical operations.

torch.manual_seed(seed=7)
x = torch.randint(low=0, high=10, size=[2, 3]).float()

print('x = ', x)

print('x * 2 = ', x*2)
print('x + 2 = ', x+2)
print('x / 2 = ', x/2)
print('x - 2 = ', x-2)

print('*'*79)

x = torch.rand(2, 3)*2 - 1.0
print('x = ', x)

print('arctan(tan(\n', x, '\n))\n=\n', torch.arctan(torch.tan(x)))
print('*'*79)
print('sin(\n', x, '\n)\n=\n', torch.sin(x))
print('*'*79)
print('arccos(\n', x, '\n)\n=\n', torch.arccos(x))
print('*'*79)
print('absolute_value(\n', x, '\n)\n=\n', torch.abs(x))  # torch.absolute also works
print('*'*79)

x =  tensor([[5., 2., 1.],
        [6., 3., 7.]])
x * 2 =  tensor([[10.,  4.,  2.],
        [12.,  6., 14.]])
x + 2 =  tensor([[7., 4., 3.],
        [8., 5., 9.]])
x / 2 =  tensor([[2.5000, 1.0000, 0.5000],
        [3.0000, 1.5000, 3.5000]])
x - 2 =  tensor([[ 3.,  0., -1.],
        [ 4.,  1.,  5.]])
*******************************************************************************
x =  tensor([[-0.5858,  0.2595, -0.2694],
        [ 0.7025,  0.7099,  0.1019]])
arctan(tan(
 tensor([[-0.5858,  0.2595, -0.2694],
        [ 0.7025,  0.7099,  0.1019]]) 
))
=
 tensor([[-0.5858,  0.2595, -0.2694],
        [ 0.7025,  0.7099,  0.1019]])
*******************************************************************************
sin(
 tensor([[-0.5858,  0.2595, -0.2694],
        [ 0.7025,  0.7099,  0.1019]]) 
)
=
 tensor([[-0.5529,  0.2566, -0.2661],
        [ 0.6462,  0.6517,  0.1017]])
*******************************************************************************
arccos(
 tensor([[-0.5858,  0.2595, -0.2694],


In [153]:
# Basic linear algebra

torch.manual_seed(seed=7)
x = torch.rand(2, 2)

print('determinant(\n', x, '\n) = ', torch.det(x))
print('*'*79)
print('eigenpair(\n', x, '\n) = ', torch.eig(input=x, eigenvectors=True))
print('*'*79)

torch.manual_seed(seed=7)
x = torch.rand(3, 2)  # SVD of a single matrix
print('svd(\n', x, '\n) = ', torch.linalg.svd(x, full_matrices=False))
u, s, v_transpose = torch.linalg.svd(x, full_matrices=False)
print('x.shape:', x.shape, 'U.shape:', u.shape, 'S.shape:', s.shape, 'V.shape:', v_transpose.shape)
print('U*S*V^T = ', u @ torch.diag_embed(s) @ v_transpose)
print('U*S*V^T = ', torch.mm(torch.mm(u, torch.diag(s)), v_transpose))
print('error(x, U*S*V^T) = ', torch.dist(torch.mm(torch.mm(u, torch.diag(s)), v_transpose), x))
print('*'*79)

torch.manual_seed(seed=7)
x = torch.rand(4, 3, 2)  # SVD of a batch of matrices
print('svd(\n', x, '\n) = ', torch.linalg.svd(x, full_matrices=False))
u, s, v_transpose = torch.linalg.svd(x, full_matrices=False)
print('x.shape:', x.shape, 'U.shape:', u.shape, 'S.shape:', s.shape, 'V.shape:', v_transpose.shape)
print('U*S*V^T = ', u @ torch.diag_embed(s) @ v_transpose)
"""
@ performs ([m, n], [n, p] -> [m, p]) matrix multiplications on [<dims>, m, n]
and [<dims>, n, p] tensors to produces [<dims>, m, p] output.
diag_embed changes a [<dims>, n] dimensional array into [<dims>, n, n] tensor
with nxn diagonal matrices for each of the rows.
"""
print('error(x, U*S*V^T) = ', torch.dist(u @ torch.diag_embed(s) @ v_transpose, x))
print('*'*79)


determinant(
 tensor([[0.5349, 0.1988],
        [0.6592, 0.6569]]) 
) =  tensor(0.2203)
*******************************************************************************
eigenpair(
 tensor([[0.5349, 0.1988],
        [0.6592, 0.6569]]) 
) =  torch.return_types.eig(
eigenvalues=tensor([[0.2288, 0.0000],
        [0.9630, 0.0000]]),
eigenvectors=tensor([[-0.5446, -0.4212],
        [ 0.8387, -0.9070]]))
*******************************************************************************
svd(
 tensor([[0.5349, 0.1988],
        [0.6592, 0.6569],
        [0.2328, 0.4251]]) 
) =  torch.return_types.linalg_svd(
U=tensor([[-0.4551,  0.7917],
        [-0.7987, -0.1606],
        [-0.3936, -0.5894]]),
S=tensor([1.1639, 0.2684]),
V=tensor([[-0.7403, -0.6723],
        [ 0.6723, -0.7403]]))
x.shape: torch.Size([3, 2]) U.shape: torch.Size([3, 2]) S.shape: torch.Size([2]) V.shape: torch.Size([2, 2])
U*S*V^T =  tensor([[0.5349, 0.1988],
        [0.6592, 0.6569],
        [0.2328, 0.4251]])
U*S*V^T =  tensor([[0.5