In [1]:
# Dependencies
import torch

import numpy as np

%matplotlib inline

In [17]:
# Create an uninitialized tensor, which has garbage and datatype float32.
x = torch.empty(size=(3, 4, 2))  # torch.empty(3, 4, 2)
print('empty tensor: {}'.format(x))
print('empty tensor type: {}'.format(x.dtype))
print('empty tensor shape: {}'.format(x.shape))

empty tensor: tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])
empty tensor type: torch.float32
empty tensor shape: torch.Size([3, 4, 2])


In [20]:
# Create a tensor of all ones. Analogously, torch.zeros works too.
ones = torch.ones(size=(3, 4, 2))
print('all ones tensor: {}'.format(ones))
print('all ones tensor type: {}'.format(ones.dtype))
print('all ones tensor shape: {}'.format(ones.shape))
zeros = torch.zeros(4, 2, 3)
print('all zeros tensor: {}'.format(zeros))
print('all zeros tensor type: {}'.format(zeros.dtype))
print('all zeros tensor shape: {}'.format(zeros.shape))

all ones tensor: tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])
all ones tensor type: torch.float32
all ones tensor shape: torch.Size([3, 4, 2])
all zeros tensor: tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
all zeros tensor type: torch.float32
all zeros tensor shape: torch.Size([4, 2, 3])


In [24]:
# Random floats from [0.0, 1.0) range.
torch.manual_seed(seed=7)
x = torch.rand(size=(3, 4, 2))
print('random tensor: {}'.format(x))
print('random tensor type: {}'.format(x.dtype))
print('random tensor shape: {}'.format(x.shape))
torch.manual_seed(seed=7)
x_again = torch.rand(size=(3, 4, 2))
print('random tensor: {}'.format(x))
print('random tensor type: {}'.format(x.dtype))
print('random tensor shape: {}'.format(x.shape))  # Identical results with manual seed.
# noinspection PyTypeChecker
print('both tensor values are the same: {}'.format(torch.all(x==x_again)))

random tensor: tensor([[[0.5349, 0.1988],
         [0.6592, 0.6569],
         [0.2328, 0.4251],
         [0.2071, 0.6297]],

        [[0.3653, 0.8513],
         [0.8549, 0.5509],
         [0.2868, 0.2063],
         [0.4451, 0.3593]],

        [[0.7204, 0.0731],
         [0.9699, 0.1078],
         [0.8829, 0.4132],
         [0.7572, 0.6948]]])
random tensor type: torch.float32
random tensor shape: torch.Size([3, 4, 2])
random tensor: tensor([[[0.5349, 0.1988],
         [0.6592, 0.6569],
         [0.2328, 0.4251],
         [0.2071, 0.6297]],

        [[0.3653, 0.8513],
         [0.8549, 0.5509],
         [0.2868, 0.2063],
         [0.4451, 0.3593]],

        [[0.7204, 0.0731],
         [0.9699, 0.1078],
         [0.8829, 0.4132],
         [0.7572, 0.6948]]])
random tensor type: torch.float32
random tensor shape: torch.Size([3, 4, 2])
both tensor values are the same: True


In [25]:
# Random ranged integers.
torch.manual_seed(seed=7)
x = torch.randint(low=0, high=10, size=(3, 4))
print('random integer tensor: {}'.format(x))
print('random integer tensor type: {}'.format(x.dtype))
print('random integer tensor shape: {}'.format(x.shape))

random integer tensor: tensor([[5, 2, 1, 6],
        [3, 7, 7, 9],
        [8, 1, 8, 1]])
random integer tensor type: torch.int64
random integer tensor shape: torch.Size([3, 4])


In [36]:
# Create tensors of the same shape.
torch.manual_seed(seed=7)
x = torch.rand(size=(3, 2, 4))
print('*'*79)
print('x: {}'.format(x))
x_empty = torch.empty_like(x)
print('*'*79)
print('empty tensor like x: {}'.format(x_empty))
print('empty tensor type like x: {}'.format(x_empty.dtype))
print('empty tensor shape like x: {}'.format(x_empty.shape))
x_ones = torch.ones_like(x)
print('*'*79)
print('all ones tensor like x: {}'.format(x_ones))
print('all ones tensor type like x: {}'.format(x_ones.dtype))
print('all ones tensor shape like x: {}'.format(x_ones.shape))
x_zeros = torch.zeros_like(x)
print('*'*79)
print('all zeros tensor like x: {}'.format(x_zeros))
print('all zeros tensor type like x: {}'.format(x_zeros.dtype))
print('all zeros tensor shape like x: {}'.format(x_zeros.shape))
x_rand = torch.rand_like(x)
print('*'*79)
print('random tensor like x: {}'.format(x_rand))
print('random tensor type like x: {}'.format(x_rand.dtype))
print('random tensor shape like x: {}'.format(x_rand.shape))
x_randint = torch.randint_like(input=x, low=0, high=10)  # The data type is cast to that of x, which is float32!
print('*'*79)
print('random integer tensor like x: {}'.format(x_randint))
print('random integer tensor like x type: {}'.format(x_randint.dtype))
print('random integer tensor like x shape: {}'.format(x_randint.shape))
x_randint = torch.randint_like(input=x, low=0, high=10, dtype=torch.int32)
print('*'*79)
print('random integer tensor like x: {}'.format(x_randint))
print('random integer tensor like x type : {}'.format(x_randint.dtype))
print('random integer tensor like x shape: {}'.format(x_randint.shape))

*******************************************************************************
x: tensor([[[0.5349, 0.1988, 0.6592, 0.6569],
         [0.2328, 0.4251, 0.2071, 0.6297]],

        [[0.3653, 0.8513, 0.8549, 0.5509],
         [0.2868, 0.2063, 0.4451, 0.3593]],

        [[0.7204, 0.0731, 0.9699, 0.1078],
         [0.8829, 0.4132, 0.7572, 0.6948]]])
*******************************************************************************
empty tensor like x: tensor([[[ 0.0000e+00,  3.6893e+19,  0.0000e+00,  3.6893e+19],
         [ 1.4013e-44,  0.0000e+00, -4.8766e+30,  4.5897e-41]],

        [[ 1.1479e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  4.9045e-44,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.1704e-41],
         [ 0.0000e+00,  2.2369e+08,  0.0000e+00,  0.0000e+00]]])
empty tensor type like x: torch.float32
empty tensor shape like x: torch.Size([3, 2, 4])
*******************************************************************************

In [42]:
# Creating a tensor from the data given.
# The tensor stores its own copy of the data.
# Note different containers used (lists and tuples).
x = torch.tensor(
    data=(
        ([1, 2, 3], (3, 4, 5)),
        ([5, 6, 7], (7, 8, 9)),
        [[10, 11, 12], [13, 14, 15]],
        ((16, 17, 18), (19, 20, 21))
    ), dtype=torch.float32
)
print('x from data: {}'.format(x))
print('x from data type: {}'.format(x.dtype))
print('x from data shape: {}'.format(x.shape))

x from data: tensor([[[ 1.,  2.,  3.],
         [ 3.,  4.,  5.]],

        [[ 5.,  6.,  7.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.]],

        [[16., 17., 18.],
         [19., 20., 21.]]])
x from data type: torch.float32
x from data shape: torch.Size([4, 2, 3])


In [67]:
# Data types by specifying the `dtype` parameter.
x = torch.rand(size=(3, 4), dtype=torch.float)  # floatX works, intX doesn't!
print('x: {}, type: {}'.format(x, x.dtype))
x = torch.randint(low=0, high=10, size=(3, 4), dtype=torch.float32)  # intX and floatX work!
print('x: {}, type: {}'.format(x, x.dtype))
x = torch.randint(low=0, high=10, size=(3, 4), dtype=torch.int)  # intX and floatX work!
print('x: {}, type: {}'.format(x, x.dtype))
# Data type by casting via attributes float(), int(), bool().
x = torch.rand(size=(3, 4)).float()  # Casts to float32.
print('x: {}, type: {}'.format(x, x.dtype))
x = torch.rand(size=(3, 4)).int()  # Casts to int32. So, it will all be zero! (why?)
print('x: {}, type: {}'.format(x, x.dtype))
x = torch.rand(size=(3, 4)).bool()  # Casts to bool. So, it will all be True! (why?)
print('x: {}, type: {}'.format(x, x.dtype))
x = torch.rand(size=(3, 4)).int().bool()  # Casts to int32 and then to bool. So, it will all be False! (why?)
print('x: {}, type: {}'.format(x, x.dtype))
# Creating a random bool tensor of `True` and `False` values.
x = torch.randint(low=0, high=2, size=(3, 4, 2), dtype=torch.bool)
print('x: {}, type: {}'.format(x, x.dtype))
# Casting with the `.to(<...>)` attribute.
x = torch.randint(low=0, high=10, size=(3, 4))
print('*'*79)
print('x: {}, type: {}'.format(x, x.dtype))
print('*'*79)
x_int = x.to(torch.int)
print('x_int: {}, type: {}'.format(x_int, x_int.dtype))
x_int8 = x.to(torch.int8)
print('x_int8: {}, type: {}'.format(x_int8, x_int8.dtype))
x_int16 = x.to(torch.int16)
print('x_int16: {}, type: {}'.format(x_int16, x_int16.dtype))
x_int32 = x.to(torch.int32)
print('x_int32: {}, type: {}'.format(x_int32, x_int32.dtype))
x_int64 = x.to(torch.int64)
print('x_int64: {}, type: {}'.format(x_int64, x_int64.dtype))
print('*'*79)
x_float = x.to(torch.float)
print('x_float: {}, type: {}'.format(x_float, x_float.dtype))
x_float16 = x.to(torch.float16)  # float8 does not exist!
print('x_float16: {}, type: {}'.format(x_float16, x_float16.dtype))
x_float32 = x.to(torch.float32)
print('x_float32: {}, type: {}'.format(x_float32, x_float32.dtype))
x_float64 = x.to(torch.float64)
print('x_float64: {}, type: {}'.format(x_float64, x_float64.dtype))
print('*'*79)
x_bool = x.to(torch.bool)
print('x_bool: {}, type: {}'.format(x_bool, x_bool.dtype))
print('*'*79)
x_uint8 = x.to(torch.uint8)
print('x_uint8: {}, type: {}'.format(x_uint8, x_uint8.dtype))

x: tensor([[0.6951, 0.7723, 0.9351, 0.2421],
        [0.5388, 0.5601, 0.2439, 0.8343],
        [0.8790, 0.5748, 0.1886, 0.8858]]), type: torch.float32
x: tensor([[7., 1., 4., 2.],
        [2., 9., 4., 5.],
        [5., 9., 4., 0.]]), type: torch.float32
x: tensor([[3, 9, 9, 0],
        [6, 4, 8, 4],
        [9, 2, 2, 3]], dtype=torch.int32), type: torch.int32
x: tensor([[0.0495, 0.9578, 0.4885, 0.6024],
        [0.3740, 0.3487, 0.1645, 0.4881],
        [0.8368, 0.6325, 0.6616, 0.1353]]), type: torch.float32
x: tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32), type: torch.int32
x: tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]]), type: torch.bool
x: tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]), type: torch.bool
x: tensor([[[ True, False],
         [ True, False],
         [ True, False],
         [False,  True]],

        [[ Tru

In [69]:
# Tensor broadcasting with addition as example. Works for other ops too!
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 3])
ans1 = x1 + x2
print('########## Result 1')
print(x1, '\n+\n', x2, '\n=\n', ans1)

# The three results below (2, 3, 4) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[3, ])
ans2 = x1 + x2
print('########## Result 2')
print(x1, '\n+\n', x2, '\n=\n', ans2)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 3])
ans3 = x1 + x2
print('########## Result 3')
print(x1, '\n+\n', x2, '\n=\n', ans3)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 1, 3])
ans4 = x1 + x2
print('########## Result 4')
print(x1, '\n+\n', x2, '\n=\n', ans4)

# The two results below (5, 6) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 3])
ans5 = x1 + x2
print('########## Result 5')
print(x1, '\n+\n', x2, '\n=\n', ans5)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 2, 3])
ans6 = x1 + x2
print('########## Result 6')
print(x1, '\n+\n', x2, '\n=\n', ans6)

# The two results below (7, 8) must match.
torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[1, 2, 1])
ans7 = x1 + x2
print('########## Result 7')
print(x1, '\n+\n', x2, '\n=\n', ans7)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 1])
ans8 = x1 + x2
print('########## Result 8')
print(x1, '\n+\n', x2, '\n=\n', ans8)

torch.manual_seed(seed=7)
x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
x2 = torch.randint(low=0, high=10, size=[2, 1, 1])
ans9 = x1 + x2
print('########## Result 9')
print(x1, '\n+\n', x2, '\n=\n', ans9)

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
# x2 = torch.randint(low=0, high=10, size=[2, ])
# print('########## Result 10')
# print(x1, '\n+\n', x2, '\n=\n', x1+x2)  # This should produce an error.

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 4])
# x2 = torch.randint(low=0, high=10, size=[1, 1, 2])
# print('########## Result 11')
# print(x1, '\n+\n', x2, '\n=\n', x1+x2)  # This should produce an error.

# torch.manual_seed(seed=7)
# x1 = torch.randint(low=0, high=10, size=[2, 2, 3])
# x2 = torch.randint(low=0, high=10, size=[2, ])
# print('########## Result 12')
# print(x1, '\n+\n', x2, '\n=\n', x1+x2)  # This should produce an error.

# noinspection PyTypeChecker
assert (torch.all(ans2==ans3) and torch.all(ans2==ans4))
# noinspection PyTypeChecker
assert torch.all(ans5==ans6)

########## Result 1
tensor([[5, 2, 1],
        [6, 3, 7]]) 
+
 tensor([[7, 9, 8],
        [1, 8, 1]]) 
=
 tensor([[12, 11,  9],
        [ 7, 11,  8]])
########## Result 2
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([8, 7, 2]) 
=
 tensor([[[13,  9,  3],
         [14, 10,  9]],

        [[15, 16, 10],
         [ 9, 15,  3]]])
########## Result 3
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([[8, 7, 2]]) 
=
 tensor([[[13,  9,  3],
         [14, 10,  9]],

        [[15, 16, 10],
         [ 9, 15,  3]]])
########## Result 4
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([[[8, 7, 2]]]) 
=
 tensor([[[13,  9,  3],
         [14, 10,  9]],

        [[15, 16, 10],
         [ 9, 15,  3]]])
########## Result 5
tensor([[[5, 2, 1],
         [6, 3, 7]],

        [[7, 9, 8],
         [1, 8, 1]]]) 
+
 tensor([[8, 7, 2],
        [0, 6, 2]]) 
=
 tensor([[[13, 

In [76]:
# Some math operations.
x = torch.rand(size=(3, 4))*10  # [0, 10) ranged random floats.
print('x: {}'.format(x))
x_abs = torch.abs(x)
print('abs(x): {}'.format(x_abs))
x_floor = torch.floor(x)
print('floor(x): {}'.format(x_floor))
x_ceil = torch.ceil(x)
print('ceil(x): {}'.format(x_ceil))
x_clamp_bet_3_and_7 = torch.clamp(x, min=3, max=7)
print('x_clamp_bet_3_and_7(x): {}'.format(x_clamp_bet_3_and_7))
x_clamp_below_by_3 = torch.clamp_min(x, min=3)
print('x_clamp_below_by_3(x): {}'.format(x_clamp_below_by_3))
x_clamp_above_by_7 = torch.clamp_max(x, max=7)
print('x_clamp_above_by_7(x): {}'.format(x_clamp_above_by_7))

x: tensor([[8.0988, 7.7435, 5.2780, 9.3559],
        [1.4697, 2.0185, 7.2591, 4.7313],
        [0.4436, 1.5392, 1.9562, 8.8611]])
abs(x): tensor([[8.0988, 7.7435, 5.2780, 9.3559],
        [1.4697, 2.0185, 7.2591, 4.7313],
        [0.4436, 1.5392, 1.9562, 8.8611]])
floor(x): tensor([[8., 7., 5., 9.],
        [1., 2., 7., 4.],
        [0., 1., 1., 8.]])
ceil(x): tensor([[ 9.,  8.,  6., 10.],
        [ 2.,  3.,  8.,  5.],
        [ 1.,  2.,  2.,  9.]])
x_clamp_bet_3_and_7(x): tensor([[7.0000, 7.0000, 5.2780, 7.0000],
        [3.0000, 3.0000, 7.0000, 4.7313],
        [3.0000, 3.0000, 3.0000, 7.0000]])
x_clamp_below_by_3(x): tensor([[8.0988, 7.7435, 5.2780, 9.3559],
        [3.0000, 3.0000, 7.2591, 4.7313],
        [3.0000, 3.0000, 3.0000, 8.8611]])
x_clamp_above_by_7(x): tensor([[7.0000, 7.0000, 5.2780, 7.0000],
        [1.4697, 2.0185, 7.0000, 4.7313],
        [0.4436, 1.5392, 1.9562, 7.0000]])


In [80]:
# Comparison operations. Broadcasting is supported
x = torch.randint(low=0, high=2, size=(2, 3))
y = torch.randint(low=0, high=2, size=(2, 3))
print('x: \n{}'.format(x))
print('y: \n{}'.format(y))
print('*'*79)
x_eq_y = torch.eq(input=x, other=y)
print('x==y: \n{}'.format(x_eq_y))
x_less_than_y = torch.less(input=x, other=y)
print('x<y: \n{}'.format(x_less_than_y))
x_less_equal_y = torch.less_equal(input=x, other=y)
print('x<=y: \n{}'.format(x_less_equal_y))
x_greater_than_y = torch.greater(input=x, other=y)
print('x>y: \n{}'.format(x_greater_than_y))
x_greater_equal_y = torch.greater_equal(input=x, other=y)
print('x>=y: \n{}'.format(x_greater_equal_y))

x: 
tensor([[1, 1, 0],
        [0, 0, 0]])
y: 
tensor([[0, 0, 0],
        [0, 0, 0]])
*******************************************************************************
x==y: 
tensor([[False, False,  True],
        [ True,  True,  True]])
x<y: 
tensor([[False, False, False],
        [False, False, False]])
x<=y: 
tensor([[False, False,  True],
        [ True,  True,  True]])
x>y: 
tensor([[ True,  True, False],
        [False, False, False]])
x>=y: 
tensor([[True, True, True],
        [True, True, True]])


In [106]:
# Reduction operations.
x = torch.randint(low=1, high=6, size=(2, 3))
print('x: \n{}'.format(x))
x_sum = torch.sum(x)
print('sum(x): \n{}'.format(x_sum))
x_mean = torch.mean(x.to(torch.float32))  # `torch.mean` only operates on float and not int/long.
print('mean(x): \n{}'.format(x_mean))
x_product = torch.prod(x)
print('product(x): \n{}'.format(x_product))
x_min = torch.min(x)
print('min(x): \n{}'.format(x_min))
x_max = torch.max(x)
print('max(x): \n{}'.format(x_max))
# Reductions along specific dimensions.
# `keepdim` enables preserving the result shape and thus, is a good practice!
print('*'*79)
x = torch.randint(low=1, high=6, size=(2, 3, 4))
print('x: \n{},\nshape: {}'.format(x, x.shape))
x_sum_dim_0 = torch.sum(x, dim=0, keepdim=True)
print('sum(x): \n{},\nshape: {}'.format(x_sum_dim_0, x_sum_dim_0.shape))
print('*'*79)
x_prod_dim_1 = torch.prod(x, dim=1, keepdim=True)
print('product(x): \n{},\nshape: {}'.format(x_prod_dim_1, x_prod_dim_1.shape))
x_mean_dim_2 = torch.mean(x.float(), dim=2, keepdim=True)  # `torch.mean` operates on floats!
print('mean(x): \n{},\nshape: {}'.format(x_mean_dim_2, x_mean_dim_2.shape))
# The next two results must match the previous two in order!
x_prod_dim_minus2 = torch.prod(x, dim=-2, keepdim=True)  # `torch.mean` operates on floats!
print('product(x): \n{},\nshape: {}'.format(x_prod_dim_minus2, x_prod_dim_minus2.shape))
x_mean_dim_minus1 = torch.mean(x.float(), dim=-1, keepdim=True)
print('mean(x): \n{},\nshape: {}'.format(x_mean_dim_minus1, x_mean_dim_minus1.shape))
# The results with negative dimensions match the standard ones!
print('results with appropriately negated dimensions match: {}'.format(
    torch.all(torch.eq(x_prod_dim_1, x_prod_dim_minus2)) and\
    torch.all(torch.eq(x_mean_dim_2, x_mean_dim_minus1))
))
# Filter unique elements.
print('*'*79)
x = torch.randint(low=0, high=10, size=(4, 3, 2))
print('x: \n{},\nshape: {}'.format(x, x.shape))
x_unique, x_indices, x_counts = torch.unique(
    input=x, sorted=True, return_inverse=True, return_counts=True, dim=None
)
print('unique elements in x: \n{}'.format(x_unique))
print('indices of unique elements in x: \n{}'.format(x_indices))
print('counts of unique elements in x: \n{}'.format(x_counts))
# The "indices" tell to which output index did the current input element was mapped.

x: 
tensor([[2, 1, 5],
        [1, 3, 4]])
sum(x): 
16
mean(x): 
2.6666667461395264
product(x): 
120
min(x): 
1
max(x): 
5
*******************************************************************************
x: 
tensor([[[1, 1, 2, 1],
         [2, 3, 3, 3],
         [3, 4, 1, 5]],

        [[4, 3, 3, 3],
         [2, 2, 3, 5],
         [3, 3, 3, 1]]]),
shape: torch.Size([2, 3, 4])
sum(x): 
tensor([[[5, 4, 5, 4],
         [4, 5, 6, 8],
         [6, 7, 4, 6]]]),
shape: torch.Size([1, 3, 4])
*******************************************************************************
product(x): 
tensor([[[ 6, 12,  6, 15]],

        [[24, 18, 27, 15]]]),
shape: torch.Size([2, 1, 4])
mean(x): 
tensor([[[1.2500],
         [2.7500],
         [3.2500]],

        [[3.2500],
         [3.0000],
         [2.5000]]]),
shape: torch.Size([2, 3, 1])
product(x): 
tensor([[[ 6, 12,  6, 15]],

        [[24, 18, 27, 15]]]),
shape: torch.Size([2, 1, 4])
mean(x): 
tensor([[[1.2500],
         [2.7500],
         [3.2500]],

  